# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.cache/wt [current_project]
set_property parent.project_path D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/prgrom/text.coe
read_verilog -library xil_defaultlib {
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/DIPswitch.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/branchcmp.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/control.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/execute.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/idecode.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/iobus.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/leddisplay.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/miniRV.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/pcUpdate.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/register.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/imports/cpu_SoC/sext.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/tubedisplay.v
  D:/codeworkplace/VS-Code-V/project/cpu_SoC/top.v
}
read_ip -quiet D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all d:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all d:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all d:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

read_ip -quiet D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/prgrom/prgrom.xci
set_property used_in_implementation false [get_files -all d:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc]

read_ip -quiet D:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/dram/dram.xci
set_property used_in_implementation false [get_files -all d:/codeworkplace/VS-Code-V/project/cpu_SoC/cpu_SoC.srcs/sources_1/ip/dram/dram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/codeworkplace/VS-Code-V/project/cpu_SoC/clock.xdc
set_property used_in_implementation false [get_files D:/codeworkplace/VS-Code-V/project/cpu_SoC/clock.xdc]

read_xdc D:/codeworkplace/VS-Code-V/project/cpu_SoC/pin.xdc
set_property used_in_implementation false [get_files D:/codeworkplace/VS-Code-V/project/cpu_SoC/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
