# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/codeworkplace/VS-Code-V/project/memory_w_r/clock.xdc

# XDC: D:/codeworkplace/VS-Code-V/project/memory_w_r/pin.xdc

# IP: ip/clk_div_1/clk_div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_div || ORIG_REF_NAME==clk_div} -quiet] -quiet
